title:            Hannaford
tagline:          "Musings about code, life and current interests"
description:      "Personal website with blog and important links"
#url: http://jekyll.gtat.me

owner:
  name:           Jamie Hannaford
  avatar:         avatar.png
  email:          jamie@limetree.org
  twitter:        jamiehannaford        
  github:         jamiehannaford
  disqus:         jamiehannaford

links:
  - title: About
    url: /about
  - title: Github
    url: https://github.com/jamiehannaford
    external: true
  - title: Twitter
    url: https://twitter.com/jamiehannaford
    external: true

timezone: Europe/Zurich
future: true
highlighter: pygments
markdown: kramdown

permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
